### ISSUE TITLE
es5 env not supported?

### ISSUE THREAD

**Issue by casp4** [NicolasReibnitz/eslint-plugin-es5-jquery-lodash#1]
```

[Error - 3:34:27 PM] Error: Failed to load config "./config/lint/eslintrc.base.json" to extend from.
Referenced from: C:\Users\Dev\Documents\...\.eslintrc.json
    at configInvalidError (C:\Users\Dev\Documents\...\node_modules\@eslint\eslintrc\lib\config-array-factory.js:290:9)
    at ConfigArrayFactory._loadExtendedShareableConfig (C:\Users\Dev\Documents...\node_modules\@eslint\eslintrc\lib\config-array-factory.js:883:23)
    at ConfigArrayFactory._loadExtends (C:\Users\Dev\Documents...\node_modules\@eslint\eslintrc\lib\config-array-factory.js:781:25)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\Users\Dev\Documents...\node_modules\@eslint\eslintrc\lib\config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (C:\Users\Dev\Documents...\node_modules\@eslint\eslintrc\lib\config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (C:\Users\Dev\Documents...\node_modules\@eslint\eslintrc\lib\config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (C:\Users\Dev\Documents\...\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (C:\Users\Dev\Documents\...\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:398:20)
[Error - 3:35:15 PM] Cannot read config file: C:\Users\Dev\Documents\...\.eslintrc.json Error: Unexpected token } in JSON at position 437
[Error - 5:57:28 PM] ESLint stack trace:
[Error - 5:57:28 PM] Error: .eslintrc.json#overrides[1] » ./config/lint/eslintrc.backend.jsonc:
	Environment key "es5" is unknown

    at C:\Users\Dev\Documents\...\node_modules\@eslint\eslintrc\lib\shared\config-validator.js:175:23
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateEnvironment (C:\Users\Dev\Documents\...\node_modules\@eslint\eslintrc\lib\shared\config-validator.js:169:34)
    at ConfigValidator.validateConfigArray (C:\Users\Dev\Documents\...\node_modules\@eslint\eslintrc\lib\shared\config-validator.js:319:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (C:\Users\Dev\Documents\...\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:493:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (C:\Users\Dev\Documents\...\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:299:21)
    at CLIEngine.isPathIgnored (C:\Users\Dev\Documents\...\node_modules\eslint\lib\cli-engine\cli-engine.js:973:18)
    at CLIEngine.executeOnText (C:\Users\Dev\Documents\...\node_modules\eslint\lib\cli-engine\cli-engine.js:884:38)
    at A.lintText (c:\Users\Dev\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js:1:167443)
    at c:\Users\Dev\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js:1:180347
```

**Comment by casp4** [comment]
You can close and delete this issue. Not needed anymore as we don't need this plugin anymore. Thanks
